### ISSUE TITLE
Creating Routes

### ISSUE THREAD

**Issue by stickmanbob** [stickmanbob/RunMapper#4]
- [x] Users can create running routes on top of the Google Maps API
- [x] Data about the route is automatically generated, such as distance
- [x] Routes are saved to the user's profile for later reference and sharing

- [x] Route creator has a button to undo waypoints, clear the map, and center on the current route

- [x] Route creator has a search bar to find and center the map on a location

- [x] Route show page has toggle-able directions panel

**Comment by ryan-mapa** [comment]
- [ ] Even out the distance between the undo, clear, and center buttons on the creation page
- [ ] Add shading on hover and cursor: pointer on all dropdowns and buttons (you might have to look around to catch them all)

**Comment by ryan-mapa** [comment]
Glorious!
